# Generated by Django 5.0.2 on 2025-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('regular', 'Regular'), ('admin', 'Admin')], default='guest', max_length=10),
        ),
    ]
