# Generated by Django 4.2.19 on 2025-02-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_roleupgraderequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="encryption_iv",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="encryption_key",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
