# Generated by Django 4.2.19 on 2025-02-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_file_encryption_iv_file_encryption_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="encryption_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
